export const email = 'dmitriy.odarchenko@gmail.com';
export const password = 'Trengotest_123';
export const bearerToken = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiY2E3MDVjMzNlOTM1YjQ4NzYyMjhmMDI4YTk1NGZhNTM2ZmUxZWIwMTlhYTgyN2YyZjM4YThiM2VjYTMzOGZkYzZmYWZmZWFlZTAyODU5OWIiLCJpYXQiOjE2OTk3OTk1ODAuMzg4MjUzLCJuYmYiOjE2OTk3OTk1ODAuMzg4MjU0LCJleHAiOjQ4MjM5MzcxODAuMzc4NjM1LCJzdWIiOiI3MTIyODEiLCJzY29wZXMiOltdfQ.fypp2mkrPRbenVIWrcyO8Kj2aNs927Jxp-o7Wqu0T_Ep5SgxqQYUjhAub5UBkNoEasbNomv8PN6cltpgIDiDWg'
